import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    marginHorizontal: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  companhia: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1F2937",
    flex: 1,
    flexShrink: 1,
    marginRight: 8,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  favoritoButton: {
    padding: 4,
  },
  precoContainer: {
    backgroundColor: "#1E40AF",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  preco: {
    fontSize: 18,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  horariosContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  horarioItem: {
    alignItems: "center",
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 4,
  },
  horario: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1F2937",
    marginBottom: 4,
  },
  label: {
    fontSize: 12,
    color: "#6B7280",
    textTransform: "uppercase",
    textAlign: "center",
    flexShrink: 1,
    minWidth: "100%",
  },
  duracaoContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    flexShrink: 1,
    minWidth: 0,
  },
  duracao: {
    fontSize: 12,
    color: "#6B7280",
    flexShrink: 1,
    minWidth: 0,
  },
  infoSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  tipoAssentoContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    flex: 1,
    marginRight: 8,
  },
  tipoAssentoText: {
    fontSize: 13,
    color: "#1E40AF",
    fontWeight: "600",
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  assentosContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#F0FDF4",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  assentosText: {
    fontSize: 13,
    color: "#065F46",
    fontWeight: "600",
    flexShrink: 1,
    minWidth: 0,
  },
  actionsSection: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  comprarButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#EFF6FF",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1E40AF",
  },
  comprarButtonText: {
    fontSize: 14,
    color: "#1E40AF",
    fontWeight: "600",
  },
});
