import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#6B7280",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
    backgroundColor: "#F9FAFB",
  },
  emptyText: {
    marginTop: 16,
    fontSize: 18,
    fontWeight: "600",
    color: "#374151",
    textAlign: "center",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 16,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1F2937",
  },
  infoCard: {
    backgroundColor: "#FFFFFF",
    margin: 20,
    borderRadius: 12,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  companhiaHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  companhiaNome: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1F2937",
    flex: 1,
    flexShrink: 1,
    marginRight: 8,
  },
  avaliacao: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  avaliacaoText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#F59E0B",
  },
  rotaContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  rotaItem: {
    flex: 1,
    alignItems: "center",
  },
  rotaCidade: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1F2937",
    marginBottom: 4,
    textAlign: "center",
    flexShrink: 1,
  },
  rotaEstado: {
    fontSize: 14,
    color: "#6B7280",
    marginBottom: 8,
    textAlign: "center",
    flexShrink: 0,
    minWidth: "100%",
  },
  rotaHorario: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1E40AF",
    marginBottom: 4,
  },
  rotaData: {
    fontSize: 12,
    color: "#6B7280",
    minWidth: "100%",
    textAlign: "center",
  },
  rotaLinha: {
    width: 60,
    alignItems: "center",
    marginHorizontal: 16,
  },
  rotaLinhaPonto: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#1E40AF",
  },
  rotaLinhaTraco: {
    width: 2,
    height: 40,
    backgroundColor: "#D1D5DB",
    marginVertical: 4,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    flexWrap: "wrap",
    gap: 12,
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  infoText: {
    fontSize: 14,
    color: "#6B7280",
    flexShrink: 1,
    minWidth: "100%",
  },
  servicosContainer: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  servicosTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1F2937",
    marginBottom: 12,
  },
  servicosList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  servicoItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#F0FDF4",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    flexShrink: 1,
    minWidth: 0,
  },
  servicoText: {
    fontSize: 12,
    color: "#065F46",
    flexShrink: 1,
    minWidth: "20%",
  },
  secaoContainer: {
    backgroundColor: "#FFFFFF",
    margin: 20,
    marginTop: 0,
    borderRadius: 12,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  secaoTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1F2937",
    marginBottom: 4,
  },
  secaoSubtitle: {
    fontSize: 14,
    color: "#6B7280",
    marginBottom: 16,
  },
  legenda: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  legendaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 1,
    minWidth: 0,
  },
  legendaCor: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    justifyContent: "center",
    alignItems: "center",
  },
  legendaText: {
    fontSize: 12,
    color: "#6B7280",
    flexShrink: 1,
    minWidth: "20%",
  },
  poltronasContainer: {
    marginTop: 8,
  },
  poltronasGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "center",
  },
  poltrona: {
    width: 50,
    height: 50,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#D1D5DB",
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  poltronaDisponivel: {
    backgroundColor: "#FFFFFF",
    borderColor: "#D1D5DB",
    opacity: 0.6,
  },
  poltronaOcupada: {
    backgroundColor: "#EF4444",
    borderColor: "#DC2626",
    opacity: 0.6,
  },
  poltronaSelecionada: {
    backgroundColor: "#1E40AF",
    borderColor: "#1E40AF",
  },
  poltronaPreferencial: {
    borderColor: "#F59E0B",
    borderWidth: 3,
  },
  poltronaNumero: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1F2937",
  },
  poltronaNumeroOcupada: {
    color: "#FFFFFF",
  },
  poltronaNumeroSelecionada: {
    color: "#FFFFFF",
  },
  janelaIcon: {
    position: "absolute",
    top: 2,
    right: 2,
  },
  emptyPoltronas: {
    padding: 40,
    alignItems: "center",
  },
  emptyPoltronasText: {
    fontSize: 14,
    color: "#6B7280",
    textAlign: "center",
  },
  resumoContainer: {
    backgroundColor: "#FFFFFF",
    margin: 20,
    marginTop: 0,
    borderRadius: 12,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  resumoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    flexWrap: "wrap",
  },
  resumoLabel: {
    fontSize: 14,
    color: "#6B7280",
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    marginRight: 8,
  },
  resumoValue: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1F2937",
    flexShrink: 0,
    textAlign: "right",
  },
  resumoRowTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
    paddingTop: 16,
    borderTopWidth: 2,
    borderTopColor: "#1E40AF",
  },
  resumoLabelTotal: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1F2937",
  },
  resumoValueTotal: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1E40AF",
  },
  continuarButton: {
    backgroundColor: "#1E40AF",
    margin: 20,
    marginTop: 0,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  continuarButtonDisabled: {
    backgroundColor: "#9CA3AF",
    opacity: 0.6,
  },
  continuarButtonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
  },
  promocaoBanner: {
    backgroundColor: "#10B981",
    marginHorizontal: 20,
    marginTop: 16,
    borderRadius: 12,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  promocaoBannerContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  promocaoBannerText: {
    flex: 1,
  },
  promocaoBannerTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  promocaoBannerSubtitle: {
    fontSize: 13,
    color: "#FFFFFF",
    opacity: 0.95,
    lineHeight: 18,
  },
});
